export enum actionType {
  FORM_SUBMIT = 'FORM_SUBMIT',
  DISPLAY_ALERT = 'DISPLAY_ALERT',
  UPDATE_MESSAGE = 'UPDATE_MESSAGE',
  UPDATE_INPUT = 'UPDATE_INPUT',
  REMOVE_ALL = 'REMOVE_ALL',
  ADD_ITEM = 'ADD_ITEM',
  EDIT_ITEM = 'EDIT_ITEM',
  EDITING_ITEM = 'EDITING_ITEM',
  TOOGLE_COMPLETE = 'TOOGLE_COMPLETE',
  DELETE_ITEM = 'DELETE_ITEM',
  GET_PROJECTS = 'GET_PROJECTS',
}
